liquid_class_aliases:
  "Water Free Single[001]": "Water Free Single"
  "Water Wet Contact[001]": "Water Wet Contact"
  "DMSO Single[001]": "DMSO Single"
  "Serum Free Single[001]": "Serum Free Single"
