// Generated by ../03-protocol-builder/tools/sync_simulator_protocol_ir_contract.py.
// Source: fluent_pipeline.protocol_ir_schema.protocol_ir_json_schema(). Do not edit by hand.
// This is a fast simulator-boundary guard; Python owns full Protocol IR validation.

export const PROTOCOL_IR_VERSION = "tecan.protocol_ir.v2" as const;
export const PROTOCOL_IR_SCHEMA_ID = "https://fluent-ai-assistance.local/schemas/protocol_ir.v2.schema.json" as const;
export const PROTOCOL_IR_REQUIRED_ROOT_FIELDS = [
  "ir_version",
  "id",
  "protocol",
  "source",
  "worktable",
  "labware",
  "reagents",
  "liquid_classes",
  "variables",
  "worklists",
  "dependencies",
  "safety_assumptions",
  "steps"
] as const;
export const PROTOCOL_IR_ROOT_FIELD_TYPES = {
  "id": "string",
  "protocol": "object",
  "source": "object",
  "worktable": "object",
  "labware": "array",
  "reagents": "array",
  "liquid_classes": "array",
  "variables": "array",
  "worklists": "array",
  "dependencies": "array",
  "safety_assumptions": "array",
  "steps": "array"
} as const;
export const PROTOCOL_IR_OPERATIONS = [
  "add_labware",
  "load_labware",
  "initialize_device",
  "move_plate",
  "move_axis_command",
  "start_move_command",
  "wait_for_async_response",
  "get_head_adapter",
  "drop_head_adapter",
  "pick_up_tips",
  "set_tips_back",
  "drop_tips",
  "mca384_get_tips",
  "mca384_drop_tips",
  "liha_get_tips",
  "liha_drop_tips",
  "aspirate",
  "dispense",
  "mix",
  "mca384_mix",
  "liha_aspirate",
  "liha_dispense",
  "liha_mix",
  "wash",
  "read_worklist",
  "loop_over_wells",
  "conditional_branch",
  "default_branch",
  "query_variable",
  "set_variable",
  "set_remaining_runtime",
  "runtime_variable_prompt",
  "prompt_user",
  "call_subroutine",
  "execute_application",
  "execute_vb_script",
  "application_driver_macro",
  "comment"
] as const;
export const PROTOCOL_IR_OPERATION_REQUIREMENTS = {
  "add_labware": {
    "requiresLabwareTarget": true,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "load_labware": {
    "requiresLabwareTarget": true,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "initialize_device": {
    "requiresLabwareTarget": false,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "move_plate": {
    "requiresLabwareTarget": true,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "move_axis_command": {
    "requiresLabwareTarget": false,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": true,
    "requiresDeviceIdentity": true
  },
  "start_move_command": {
    "requiresLabwareTarget": false,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": true
  },
  "wait_for_async_response": {
    "requiresLabwareTarget": false,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "get_head_adapter": {
    "requiresLabwareTarget": false,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "drop_head_adapter": {
    "requiresLabwareTarget": false,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "pick_up_tips": {
    "requiresLabwareTarget": true,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "set_tips_back": {
    "requiresLabwareTarget": true,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "drop_tips": {
    "requiresLabwareTarget": true,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "mca384_get_tips": {
    "requiresLabwareTarget": true,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "mca384_drop_tips": {
    "requiresLabwareTarget": true,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "liha_get_tips": {
    "requiresLabwareTarget": true,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "liha_drop_tips": {
    "requiresLabwareTarget": true,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "aspirate": {
    "requiresLabwareTarget": true,
    "requiresVolume": true,
    "requiresLiquidClass": true,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "dispense": {
    "requiresLabwareTarget": true,
    "requiresVolume": true,
    "requiresLiquidClass": true,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "mix": {
    "requiresLabwareTarget": true,
    "requiresVolume": true,
    "requiresLiquidClass": true,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "mca384_mix": {
    "requiresLabwareTarget": true,
    "requiresVolume": true,
    "requiresLiquidClass": true,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "liha_aspirate": {
    "requiresLabwareTarget": true,
    "requiresVolume": true,
    "requiresLiquidClass": true,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "liha_dispense": {
    "requiresLabwareTarget": true,
    "requiresVolume": true,
    "requiresLiquidClass": true,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "liha_mix": {
    "requiresLabwareTarget": true,
    "requiresVolume": true,
    "requiresLiquidClass": true,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "wash": {
    "requiresLabwareTarget": false,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "read_worklist": {
    "requiresLabwareTarget": false,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "loop_over_wells": {
    "requiresLabwareTarget": false,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "conditional_branch": {
    "requiresLabwareTarget": false,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "default_branch": {
    "requiresLabwareTarget": false,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "query_variable": {
    "requiresLabwareTarget": false,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "set_variable": {
    "requiresLabwareTarget": false,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "set_remaining_runtime": {
    "requiresLabwareTarget": false,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "runtime_variable_prompt": {
    "requiresLabwareTarget": false,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "prompt_user": {
    "requiresLabwareTarget": false,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "call_subroutine": {
    "requiresLabwareTarget": false,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "execute_application": {
    "requiresLabwareTarget": false,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "execute_vb_script": {
    "requiresLabwareTarget": false,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "application_driver_macro": {
    "requiresLabwareTarget": false,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  },
  "comment": {
    "requiresLabwareTarget": false,
    "requiresVolume": false,
    "requiresLiquidClass": false,
    "requiresMotionPosition": false,
    "requiresDeviceIdentity": false
  }
} as const;

export type ProtocolIrOperation = (typeof PROTOCOL_IR_OPERATIONS)[number];
export type ProtocolIrRootField = (typeof PROTOCOL_IR_REQUIRED_ROOT_FIELDS)[number];
export type ProtocolIrRootFieldType = (typeof PROTOCOL_IR_ROOT_FIELD_TYPES)[keyof typeof PROTOCOL_IR_ROOT_FIELD_TYPES];
export type ProtocolIrRecord = Record<string, unknown>;

export type ProtocolIrStep = ProtocolIrRecord & {
  id: string;
  index: number;
  group: string;
  operation: ProtocolIrOperation;
  name: string;
  parameters: ProtocolIrRecord;
};

export type ProtocolIrDocument = ProtocolIrRecord & {
  ir_version: typeof PROTOCOL_IR_VERSION;
  id: string;
  protocol: ProtocolIrRecord;
  source: ProtocolIrRecord;
  worktable: ProtocolIrRecord;
  labware: unknown[];
  reagents: unknown[];
  liquid_classes: unknown[];
  variables: unknown[];
  worklists: unknown[];
  dependencies: unknown[];
  safety_assumptions: unknown[];
  steps: ProtocolIrStep[];
};

export type ProtocolIrContractIssue = {
  path: string;
  message: string;
};

export type ProtocolIrContractResult = {
  value?: ProtocolIrDocument;
  issues: ProtocolIrContractIssue[];
};

function isRecord(value: unknown): value is ProtocolIrRecord {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function matchesRootFieldType(value: unknown, expected: ProtocolIrRootFieldType): boolean {
  if (expected === "array") return Array.isArray(value);
  if (expected === "object") return isRecord(value);
  return typeof value === expected;
}

function isPositiveInteger(value: unknown): value is number {
  return typeof value === "number" && Number.isInteger(value) && value >= 1;
}

function hasLabwareTarget(step: ProtocolIrRecord): boolean {
  return ["target_labware", "source_labware", "destination_labware"].some(
    (field) => typeof step[field] === "string" && step[field].length > 0
  );
}

function hasVolume(step: ProtocolIrRecord): boolean {
  const parameters = isRecord(step.parameters) ? step.parameters : {};
  return ["volume_ul", "volume_ul_expression"].some(
    (field) => field in step || field in parameters
  );
}

function hasParameter(step: ProtocolIrRecord, field: string): boolean {
  const parameters = isRecord(step.parameters) ? step.parameters : {};
  const value = parameters[field];
  return value !== undefined && value !== null && value !== "";
}

function hasDeviceIdentity(step: ProtocolIrRecord): boolean {
  return hasParameter(step, "available_id") || hasParameter(step, "id_label");
}

export function validateProtocolIr(value: unknown): ProtocolIrContractResult {
  const issues: ProtocolIrContractIssue[] = [];
  if (!isRecord(value)) {
    return { issues: [{ path: "$", message: "must be an object" }] };
  }

  if (value.ir_version !== PROTOCOL_IR_VERSION) {
    issues.push({ path: "$.ir_version", message: `must equal ${PROTOCOL_IR_VERSION}` });
  }
  for (const field of PROTOCOL_IR_REQUIRED_ROOT_FIELDS) {
    if (!(field in value)) {
      issues.push({ path: `$.${field}`, message: "is required" });
      continue;
    }
    if (field !== "ir_version" && !matchesRootFieldType(value[field], PROTOCOL_IR_ROOT_FIELD_TYPES[field])) {
      issues.push({ path: `$.${field}`, message: `must be ${PROTOCOL_IR_ROOT_FIELD_TYPES[field]}` });
    }
  }

  if (isRecord(value.protocol) && typeof value.protocol.name !== "string") {
    issues.push({ path: "$.protocol.name", message: "is required and must be a string" });
  }
  if (isRecord(value.source) && typeof value.source.format !== "string") {
    issues.push({ path: "$.source.format", message: "is required and must be a string" });
  }
  if (Array.isArray(value.steps)) {
    value.steps.forEach((step, index) => {
      const path = `$.steps[${index}]`;
      if (!isRecord(step)) {
        issues.push({ path, message: "must be an object" });
        return;
      }
      if (typeof step.id !== "string") issues.push({ path: `${path}.id`, message: "is required and must be a string" });
      if (!isPositiveInteger(step.index)) {
        issues.push({ path: `${path}.index`, message: "is required and must be a positive integer" });
      }
      if (typeof step.group !== "string") issues.push({ path: `${path}.group`, message: "is required and must be a string" });
      if (typeof step.name !== "string") issues.push({ path: `${path}.name`, message: "is required and must be a string" });
      if (!isRecord(step.parameters)) issues.push({ path: `${path}.parameters`, message: "is required and must be an object" });
      const operation = step.operation;
      if (typeof operation !== "string" || !PROTOCOL_IR_OPERATIONS.includes(operation as ProtocolIrOperation)) {
        issues.push({ path: `${path}.operation`, message: "is required and must be a registered operation" });
        return;
      }
      const requirements = PROTOCOL_IR_OPERATION_REQUIREMENTS[operation as ProtocolIrOperation];
      if (requirements.requiresLabwareTarget && !hasLabwareTarget(step)) {
        issues.push({ path, message: "operation requires target_labware, source_labware, or destination_labware" });
      }
      if (requirements.requiresVolume && !hasVolume(step)) {
        issues.push({ path, message: "operation requires volume_ul or volume_ul_expression" });
      }
      if (requirements.requiresLiquidClass && !("liquid_class" in step)) {
        issues.push({ path: `${path}.liquid_class`, message: "operation requires liquid_class" });
      }
      if (requirements.requiresMotionPosition && !hasParameter(step, "position_expression")) {
        issues.push({ path: `${path}.parameters.position_expression`, message: "operation requires position_expression" });
      }
      if (requirements.requiresDeviceIdentity && !hasDeviceIdentity(step)) {
        issues.push({ path: `${path}.parameters`, message: "operation requires available_id or id_label" });
      }
    });
  }

  return issues.length ? { issues } : { value: value as ProtocolIrDocument, issues };
}

export function isProtocolIrDocument(value: unknown): value is ProtocolIrDocument {
  return validateProtocolIr(value).issues.length === 0;
}
