"""Typed FluentControl expression support."""

from .ast import (
    BinaryExpression,
    BooleanLiteral,
    Expression,
    FunctionCall,
    NumberLiteral,
    ReviewedRawExpression,
    SourcePreservedExpression,
    StringLiteral,
    UnaryExpression,
    VariableReference,
    expression_from_mapping,
    expression_kind,
    expression_to_mapping,
    is_expression,
)
from .migration import (
    LegacyMigrationError,
    coerce_literal_expression,
    coerce_source_expression,
    expression_initial_value_text,
    expression_python_value,
    extract_opaque_expression_references,
    migrate_legacy_set_variable_value,
    parse_or_preserve_source_expression,
)
from .parser import ExpressionParseError, parse_expression, try_parse_expression
from .operators import (
    BINARY_OPERATOR_DEFINITIONS,
    BinaryOperatorDefinition,
    BinaryOperatorTypeResult,
    evaluate_binary_operator,
    infer_binary_operator_type,
)
from .renderer import ExpressionRenderError, render_expression, render_string_literal
from .semantics import (
    ExpressionSemanticContext,
    FunctionSignature,
    SemanticIssue,
    SemanticResult,
    VariableSymbol,
    check_expression_semantics,
    default_function_signatures,
    normalize_fluent_type_name,
    semantic_context_from_variables,
)
from .validation import (
    FLUENTCONTROL_SYSTEM_VARIABLES,
    expression_inventory_from_xscr_text,
    expression_inventory_from_zeia,
    expression_inventory_ok,
)
from .walker import (
    EXPRESSION_KINDS,
    ExpressionWalkRecord,
    is_expression_key,
    is_expression_mapping,
    walk_expression_values,
)
from .fields import (
    EXPRESSION_FIELDS,
    canonical_expression_command_id,
    canonical_expression_key,
    expression_fields_for_command,
    is_expression_field,
    loop_count_expression_error,
    registered_expression_field_paths,
    registered_expression_keys,
)

__all__ = [
    "BinaryExpression",
    "BINARY_OPERATOR_DEFINITIONS",
    "BinaryOperatorDefinition",
    "BinaryOperatorTypeResult",
    "BooleanLiteral",
    "Expression",
    "ExpressionParseError",
    "ExpressionRenderError",
    "ExpressionSemanticContext",
    "FunctionCall",
    "FunctionSignature",
    "LegacyMigrationError",
    "NumberLiteral",
    "ReviewedRawExpression",
    "SemanticIssue",
    "SemanticResult",
    "SourcePreservedExpression",
    "StringLiteral",
    "UnaryExpression",
    "VariableSymbol",
    "VariableReference",
    "check_expression_semantics",
    "coerce_literal_expression",
    "coerce_source_expression",
    "default_function_signatures",
    "expression_from_mapping",
    "expression_initial_value_text",
    "extract_opaque_expression_references",
    "expression_inventory_from_xscr_text",
    "expression_inventory_from_zeia",
    "expression_inventory_ok",
    "EXPRESSION_FIELDS",
    "EXPRESSION_KINDS",
    "ExpressionWalkRecord",
    "FLUENTCONTROL_SYSTEM_VARIABLES",
    "canonical_expression_command_id",
    "canonical_expression_key",
    "expression_fields_for_command",
    "is_expression_field",
    "loop_count_expression_error",
    "registered_expression_field_paths",
    "registered_expression_keys",
    "expression_kind",
    "expression_python_value",
    "expression_to_mapping",
    "evaluate_binary_operator",
    "is_expression",
    "is_expression_key",
    "is_expression_mapping",
    "infer_binary_operator_type",
    "migrate_legacy_set_variable_value",
    "normalize_fluent_type_name",
    "parse_expression",
    "parse_or_preserve_source_expression",
    "render_expression",
    "render_string_literal",
    "semantic_context_from_variables",
    "try_parse_expression",
    "walk_expression_values",
]
