"""Generate the simulator's bounded Protocol IR contract from the canonical schema.

The TypeScript validator intentionally checks the transport boundary only. Full
semantic validation remains owned by ``fluent_pipeline.protocol_ir_schema``.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from fluent_pipeline.protocol_ir_schema import CURRENT_PROTOCOL_IR_VERSION, protocol_ir_json_schema


SOURCE_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = SOURCE_ROOT / "04-protocol-simulator" / "src" / "data" / "protocolIrContract.ts"


def _json(value: Any, *, indent: int = 2) -> str:
    return json.dumps(value, indent=indent, ensure_ascii=False)


def _root_field_type(property_schema: dict[str, Any]) -> str:
    if "$ref" in property_schema:
        return "object"
    value_type = property_schema.get("type")
    if isinstance(value_type, str):
        return value_type
    raise ValueError(f"Unsupported root property type: {property_schema!r}")


def _rule_operations(rule: dict[str, Any]) -> set[str]:
    operation = rule.get("if", {}).get("properties", {}).get("operation", {})
    return set(operation.get("enum", []))


def _rule_requires(rule: dict[str, Any], field: str) -> bool:
    def contains_required(value: Any) -> bool:
        if isinstance(value, dict):
            return field in value.get("required", []) or any(contains_required(item) for item in value.values())
        if isinstance(value, list):
            return any(contains_required(item) for item in value)
        return False

    return contains_required(rule.get("then", {}))


def _operation_requirements(schema: dict[str, Any], operations: list[str]) -> dict[str, dict[str, bool]]:
    requirements = {
        operation: {
            "requiresLabwareTarget": False,
            "requiresVolume": False,
            "requiresLiquidClass": False,
        }
        for operation in operations
    }
    for rule in schema["$defs"]["step"].get("allOf", []):
        for operation in _rule_operations(rule):
            if operation not in requirements:
                continue
            requirements[operation]["requiresLabwareTarget"] |= any(
                _rule_requires(rule, field)
                for field in ("target_labware", "source_labware", "destination_labware")
            )
            requirements[operation]["requiresVolume"] |= _rule_requires(rule, "volume_ul")
            requirements[operation]["requiresLiquidClass"] |= _rule_requires(rule, "liquid_class")
    return requirements


def render_protocol_ir_contract() -> str:
    """Render the checked-in TypeScript boundary contract deterministically."""
    schema = protocol_ir_json_schema()
    root_fields = schema["required"]
    root_field_types = {
        field: _root_field_type(schema["properties"][field])
        for field in root_fields
        if field != "ir_version"
    }
    step_schema = schema["$defs"]["step"]
    operations = step_schema["properties"]["operation"]["enum"]
    requirements = _operation_requirements(schema, operations)

    return f'''// Generated by ../03-protocol-builder/tools/sync_simulator_protocol_ir_contract.py.
// Source: fluent_pipeline.protocol_ir_schema.protocol_ir_json_schema(). Do not edit by hand.
// This is a fast simulator-boundary guard; Python owns full Protocol IR validation.

export const PROTOCOL_IR_VERSION = {_json(CURRENT_PROTOCOL_IR_VERSION)} as const;
export const PROTOCOL_IR_SCHEMA_ID = {_json(schema["$id"])} as const;
export const PROTOCOL_IR_REQUIRED_ROOT_FIELDS = {_json(root_fields)} as const;
export const PROTOCOL_IR_ROOT_FIELD_TYPES = {_json(root_field_types)} as const;
export const PROTOCOL_IR_OPERATIONS = {_json(operations)} as const;
export const PROTOCOL_IR_OPERATION_REQUIREMENTS = {_json(requirements)} as const;

export type ProtocolIrOperation = (typeof PROTOCOL_IR_OPERATIONS)[number];
export type ProtocolIrRootField = (typeof PROTOCOL_IR_REQUIRED_ROOT_FIELDS)[number];
export type ProtocolIrRootFieldType = (typeof PROTOCOL_IR_ROOT_FIELD_TYPES)[keyof typeof PROTOCOL_IR_ROOT_FIELD_TYPES];
export type ProtocolIrRecord = Record<string, unknown>;

export type ProtocolIrStep = ProtocolIrRecord & {{
  id: string;
  index: number;
  group: string;
  operation: ProtocolIrOperation;
  name: string;
  parameters: ProtocolIrRecord;
}};

export type ProtocolIrDocument = ProtocolIrRecord & {{
  ir_version: typeof PROTOCOL_IR_VERSION;
  id: string;
  protocol: ProtocolIrRecord;
  source: ProtocolIrRecord;
  worktable: ProtocolIrRecord;
  labware: unknown[];
  reagents: unknown[];
  liquid_classes: unknown[];
  variables: unknown[];
  worklists: unknown[];
  dependencies: unknown[];
  safety_assumptions: unknown[];
  steps: ProtocolIrStep[];
}};

export type ProtocolIrContractIssue = {{
  path: string;
  message: string;
}};

export type ProtocolIrContractResult = {{
  value?: ProtocolIrDocument;
  issues: ProtocolIrContractIssue[];
}};

function isRecord(value: unknown): value is ProtocolIrRecord {{
  return typeof value === "object" && value !== null && !Array.isArray(value);
}}

function matchesRootFieldType(value: unknown, expected: ProtocolIrRootFieldType): boolean {{
  if (expected === "array") return Array.isArray(value);
  if (expected === "object") return isRecord(value);
  return typeof value === expected;
}}

function isPositiveInteger(value: unknown): value is number {{
  return typeof value === "number" && Number.isInteger(value) && value >= 1;
}}

function hasLabwareTarget(step: ProtocolIrRecord): boolean {{
  return ["target_labware", "source_labware", "destination_labware"].some(
    (field) => typeof step[field] === "string" && step[field].length > 0
  );
}}

function hasVolume(step: ProtocolIrRecord): boolean {{
  const parameters = isRecord(step.parameters) ? step.parameters : {{}};
  return ["volume_ul", "volume_ul_expression"].some(
    (field) => field in step || field in parameters
  );
}}

export function validateProtocolIr(value: unknown): ProtocolIrContractResult {{
  const issues: ProtocolIrContractIssue[] = [];
  if (!isRecord(value)) {{
    return {{ issues: [{{ path: "$", message: "must be an object" }}] }};
  }}

  if (value.ir_version !== PROTOCOL_IR_VERSION) {{
    issues.push({{ path: "$.ir_version", message: `must equal ${{PROTOCOL_IR_VERSION}}` }});
  }}
  for (const field of PROTOCOL_IR_REQUIRED_ROOT_FIELDS) {{
    if (!(field in value)) {{
      issues.push({{ path: `$.${{field}}`, message: "is required" }});
      continue;
    }}
    if (field !== "ir_version" && !matchesRootFieldType(value[field], PROTOCOL_IR_ROOT_FIELD_TYPES[field])) {{
      issues.push({{ path: `$.${{field}}`, message: `must be ${{PROTOCOL_IR_ROOT_FIELD_TYPES[field]}}` }});
    }}
  }}

  if (isRecord(value.protocol) && typeof value.protocol.name !== "string") {{
    issues.push({{ path: "$.protocol.name", message: "is required and must be a string" }});
  }}
  if (isRecord(value.source) && typeof value.source.format !== "string") {{
    issues.push({{ path: "$.source.format", message: "is required and must be a string" }});
  }}
  if (Array.isArray(value.steps)) {{
    value.steps.forEach((step, index) => {{
      const path = `$.steps[${{index}}]`;
      if (!isRecord(step)) {{
        issues.push({{ path, message: "must be an object" }});
        return;
      }}
      if (typeof step.id !== "string") issues.push({{ path: `${{path}}.id`, message: "is required and must be a string" }});
      if (!isPositiveInteger(step.index)) {{
        issues.push({{ path: `${{path}}.index`, message: "is required and must be a positive integer" }});
      }}
      if (typeof step.group !== "string") issues.push({{ path: `${{path}}.group`, message: "is required and must be a string" }});
      if (typeof step.name !== "string") issues.push({{ path: `${{path}}.name`, message: "is required and must be a string" }});
      if (!isRecord(step.parameters)) issues.push({{ path: `${{path}}.parameters`, message: "is required and must be an object" }});
      const operation = step.operation;
      if (typeof operation !== "string" || !PROTOCOL_IR_OPERATIONS.includes(operation as ProtocolIrOperation)) {{
        issues.push({{ path: `${{path}}.operation`, message: "is required and must be a registered operation" }});
        return;
      }}
      const requirements = PROTOCOL_IR_OPERATION_REQUIREMENTS[operation as ProtocolIrOperation];
      if (requirements.requiresLabwareTarget && !hasLabwareTarget(step)) {{
        issues.push({{ path, message: "operation requires target_labware, source_labware, or destination_labware" }});
      }}
      if (requirements.requiresVolume && !hasVolume(step)) {{
        issues.push({{ path, message: "operation requires volume_ul or volume_ul_expression" }});
      }}
      if (requirements.requiresLiquidClass && !("liquid_class" in step)) {{
        issues.push({{ path: `${{path}}.liquid_class`, message: "operation requires liquid_class" }});
      }}
    }});
  }}

  return issues.length ? {{ issues }} : {{ value: value as ProtocolIrDocument, issues }};
}}

export function isProtocolIrDocument(value: unknown): value is ProtocolIrDocument {{
  return validateProtocolIr(value).issues.length === 0;
}}
'''


def sync_protocol_ir_contract(output: Path = DEFAULT_OUTPUT, *, check: bool = False) -> bool:
    """Write the contract, or return whether the checked-in output is current."""
    rendered = render_protocol_ir_contract()
    if check:
        return output.is_file() and output.read_text(encoding="utf-8") == rendered
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync Protocol IR contract for the simulator.")
    parser.add_argument("--check", action="store_true", help="fail when the checked-in contract is stale")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="contract file to write or check")
    args = parser.parse_args()
    current = sync_protocol_ir_contract(args.output, check=args.check)
    if args.check and not current:
        print(f"Protocol IR simulator contract is stale: {args.output}")
        return 1
    print(f"Protocol IR simulator contract {'checked' if args.check else 'written'}: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
