"""Compatibility wrapper around :mod:`tecan_common.gwl`."""

from tecan_common.gwl import (  # noqa: F401
    Break,
    Comment,
    Flush,
    Pipette,
    RawRecord,
    Record,
    SetDiTiType,
    SUPPORTED_SIMPLE_TIP_CHANNELS,
    TipSelection,
    Wash,
    Worklist,
    parse_tip_selection,
    parse_gwl,
    parse_gwl_line,
    parse_gwl_lines,
    parse_gwl_text,
    serialize_gwl,
)

__all__ = [
    "Break",
    "Comment",
    "Flush",
    "Pipette",
    "RawRecord",
    "Record",
    "SetDiTiType",
    "SUPPORTED_SIMPLE_TIP_CHANNELS",
    "TipSelection",
    "Wash",
    "Worklist",
    "parse_tip_selection",
    "parse_gwl",
    "parse_gwl_line",
    "parse_gwl_lines",
    "parse_gwl_text",
    "serialize_gwl",
]
