"""CLI implementation package for fluent_pipeline."""

from __future__ import annotations

from ..application_services import (
    analyze_logs,
    apply_repair,
    create_request_spec,
    generate_protocol,
    import_project,
    inspect_project,
    plan_repair,
    validate_request_spec,
    verify_bundle,
)
from ..diagnostics import diagnose_input
from ..generation_workflow import run_generation_workflow
from ..script_analysis import analyze_script
from .rendering import (
    bundle_verification_exit_code,
    generation_exit_code,
    generation_simulator_bundle,
    log_analysis_exit_code,
    print_bundle_verification_result,
    print_generation_result,
    print_log_analysis_result,
    print_project_import_result,
    print_project_inspection_result,
    print_repair_apply_result,
    print_repair_plan_result,
    print_request_spec_result,
    print_request_spec_validation_result,
    progress_callback_from_mode,
    request_spec_validation_exit_code,
)
from .requests import (
    bundle_verification_request_from_cli,
    generation_request_from_cli,
    log_analysis_request_from_cli,
    project_import_request_from_cli,
    project_inspection_request_from_cli,
    repair_apply_request_from_cli,
    repair_plan_request_from_cli,
    request_spec_create_request_from_cli,
    request_spec_validation_request_from_cli,
)
from .commands.diagnostics import (
    _cmd_analyze,
    _cmd_diagnose,
    _cmd_map_media,
    _cmd_parse_fluent_log,
    _cmd_process_media,
    _cmd_template_info,
    _cmd_template_list,
)
from .commands.doctor import _cmd_compatibility_matrix, _cmd_doctor, _cmd_setup
from .commands.generation import (
    _cmd_bundle_lifecycle,
    _cmd_compile,
    _cmd_decompile,
    _cmd_determinism_check,
    _cmd_generate,
    _cmd_ir_build,
    _cmd_ir_export,
    _cmd_ir_schema,
    _cmd_repair_draft,
    _cmd_repair_plan,
    _cmd_roundtrip,
    _generation_context_from_args,
    _resolve_generation_event_log,
    _resolve_ir_source,
)
from .commands.projects import (
    _cmd_alias_list,
    _cmd_alias_normalize_ir,
    _cmd_alias_resolve,
    _cmd_catalog_find,
    _cmd_catalog_info,
    _cmd_clear_project,
    _cmd_collection_info,
    _cmd_create_collection,
    _cmd_current_project,
    _cmd_import_project,
    _cmd_inspect_external_command,
    _cmd_list_collections,
    _cmd_list_projects,
    _cmd_project_find,
    _cmd_project_info,
    _cmd_script_report,
    _cmd_use_project,
)
from .commands.simulator import _cmd_launch_simulator, _cmd_simulate
from .commands.validation import (
    _cmd_fluent_prepare_check,
    _cmd_ir_validate,
    _cmd_request_spec,
    _cmd_resolve_spec,
    _cmd_validate_delivery_bundle,
    _cmd_validate_spec,
    _cmd_verify_bundle,
    _cmd_worktable_diff,
)
from .runtime import _command_context, main

__all__ = [
    "analyze_script",
    "analyze_logs",
    "apply_repair",
    "bundle_verification_exit_code",
    "bundle_verification_request_from_cli",
    "create_request_spec",
    "diagnose_input",
    "generate_protocol",
    "generation_exit_code",
    "generation_request_from_cli",
    "generation_simulator_bundle",
    "import_project",
    "inspect_project",
    "log_analysis_exit_code",
    "log_analysis_request_from_cli",
    "main",
    "plan_repair",
    "print_bundle_verification_result",
    "print_generation_result",
    "print_log_analysis_result",
    "print_project_import_result",
    "print_project_inspection_result",
    "print_repair_apply_result",
    "print_repair_plan_result",
    "print_request_spec_result",
    "print_request_spec_validation_result",
    "progress_callback_from_mode",
    "project_import_request_from_cli",
    "project_inspection_request_from_cli",
    "repair_apply_request_from_cli",
    "repair_plan_request_from_cli",
    "request_spec_create_request_from_cli",
    "request_spec_validation_exit_code",
    "request_spec_validation_request_from_cli",
    "run_generation_workflow",
    "validate_request_spec",
    "verify_bundle",
    "_cmd_alias_list",
    "_cmd_alias_normalize_ir",
    "_cmd_alias_resolve",
    "_cmd_analyze",
    "_cmd_bundle_lifecycle",
    "_cmd_catalog_find",
    "_cmd_catalog_info",
    "_cmd_clear_project",
    "_cmd_collection_info",
    "_cmd_compatibility_matrix",
    "_cmd_compile",
    "_cmd_create_collection",
    "_cmd_current_project",
    "_cmd_decompile",
    "_cmd_determinism_check",
    "_cmd_diagnose",
    "_cmd_doctor",
    "_cmd_fluent_prepare_check",
    "_cmd_generate",
    "_cmd_import_project",
    "_cmd_inspect_external_command",
    "_cmd_ir_build",
    "_cmd_ir_export",
    "_cmd_ir_schema",
    "_cmd_ir_validate",
    "_cmd_launch_simulator",
    "_cmd_list_collections",
    "_cmd_list_projects",
    "_cmd_map_media",
    "_cmd_parse_fluent_log",
    "_cmd_process_media",
    "_cmd_project_find",
    "_cmd_project_info",
    "_cmd_repair_draft",
    "_cmd_repair_plan",
    "_cmd_request_spec",
    "_cmd_resolve_spec",
    "_cmd_roundtrip",
    "_cmd_script_report",
    "_cmd_setup",
    "_cmd_simulate",
    "_cmd_template_info",
    "_cmd_template_list",
    "_cmd_use_project",
    "_cmd_validate_delivery_bundle",
    "_cmd_validate_spec",
    "_cmd_verify_bundle",
    "_cmd_worktable_diff",
    "_command_context",
    "_generation_context_from_args",
    "_resolve_generation_event_log",
    "_resolve_ir_source",
]
